---
- name: install epel
  yum:
    name:
      - epel-*
    state: latest

- name: Install
  package: 
    name:
      - borgbackup
    state: latest

- name: mount share for pub key
  mount:
    src: 192.168.10.10:/var/share
    path: /mnt
    state: mounted
    fstype: nfs

- name: gen ssh key
  user:
    name: root
    generate_ssh_key: yes

- name: copy key 
  copy: 
    src: /root/.ssh/id_rsa.pub
    dest: /mnt
    remote_src: yes

- name: "copy ssh conf"
  copy:
    src: sshconfig
    dest: /root/.ssh/config

- name: "Copy backup.service"
  copy:
    src: '{{item}}'
    dest: /etc/systemd/system
  loop:
    - backup.service
    - backup.timer

- name: "Enable backup every 1 min"
  systemd:
    name: 'backup.{{item}}'
    state: started
    enabled: yes
    daemon-reload: yes
  loop:
    - timer
    - service